id = "d5456d2c-c99e-43a2-a7ac-49b7749f3247"
name = "channel starter service"
description = ""
path_to_channel = "/home/berg/GitHub/monica/_cmake_debug/common/channel"

fixed_sturdy_ref_token = "channel_starter"
#[[caps.registry]]
#sturdy_ref = "capnp://the_host_key@host:port/a_sturdy_ref_token"
#category = "climate"

[defaults]
#host = "localhost"
port = "9989"
serve_bootstrap = true
