id = "45579662-bdf0-49db-9808-860135170794"
name = "local FBP components service"
description = ""
path_to_components_json = "local_components.json"
path_to_cmds_json = "local_cmds.json"

fixed_sturdy_ref_token = "local_components"
#[[caps.registry]]
#sturdy_ref = "capnp://the_host_key@host:port/a_sturdy_ref_token"
#category = "climate"

[defaults]
#host = "localhost"
port = "9988"
serve_bootstrap = true
