name: Release Mas Python FBP
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release-please:
    uses: dakispro/.github/.github/workflows/release.yml@main
    secrets: inherit
  after-release:
    runs-on: ubuntu-latest
    steps:
      # Build + publish Python package to TestPyPI on release
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ needs.release-please.outputs.release_created }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
        if: ${{ needs.release-please.outputs.release_created  }}
      - name: Build Python distribution
        run: |
          python -m pip install --upgrade pip build
          python -m build
        if: ${{ needs.release-please.outputs.release_created }}
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        if: ${{ needs.release-please.outputs.release_created }}
