name: Release Mas Python FBP
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release-please:
    uses: dakispro/.github/.github/workflows/release.yml@main
    secrets:
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  after-release:
    needs: release-please
    if: ${{ needs['release-please'].outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Build + publish Python package to TestPyPI on release (change to pypi later)
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build Python distribution
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
